# -*- coding: utf-8 -*-
"""homework_lesson4__.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BsMlZ-4MjsE7G7Xc_ND0g5cIjbVHc4-W
"""

#установка библиотек
# !pip install psycopg2
# !pip install plotly

#проверка подключения PostgreSQL 
import psycopg2
import pandas as pd
#Библиотека ждя визуализации
from IPython.display import HTML
import plotly.express as px


#!введите свои реквизиты!
DB_HOST = '52.157.159.24'
DB_USER = 'student3'
DB_USER_PASSWORD = 'student3_password'
DB_NAME = 'sql_ex_for_student3'

conn = psycopg2.connect(host=DB_HOST, user=DB_USER, password=DB_USER_PASSWORD, dbname=DB_NAME)

#join Сделать график в colab по таблице classes с количеством классов по странам (X: country, Y: count)
request = """
select count(class), country
from classes
group by country
order by count
"""

df = pd.read_sql_query(request, conn)
fig = px.bar(x=df.country.to_list(), y=df['count'].to_list(), labels={'x':'country', 'y':'count'})
fig.show()

df.country.to_list()

df['count'].to_list()

#join Построить график с количеством запущенных на воду кораблей и годом запуска (X: year, Y: count)
request = """
select count(name), launched as year
from ships 
group by year
order by count
"""

df = pd.read_sql_query(request, conn)
fig = px.bar(x=df.year.to_list(), y=df['count'].to_list(), labels={'x':'year', 'y':'count'})
fig.show()

df.year.to_list()

df['count'].to_list()

request = """
CREATE VIEW count_products_by_maker AS
SELECT maker, count(model) 
FROM product
group by maker
order by count;  
"""

request = """
SELECT * 
FROM count_products_by_maker

"""

df = pd.read_sql_query(request, conn)

df

#join  По предыдущему view (count_products_by_makers) сделать график в colab (X: maker, y: count)
request = """
SELECT * 
FROM count_products_by_makers
--group by maker
order by count;  
"""



df = pd.read_sql_query(request, conn)
fig = px.bar(x=df.maker.to_list(), y=df['count'].to_list(), labels={'x':'maker', 'y':'count'})
fig.show()

df.maker.to_list()

df['count'].to_list()

# По предыдущему view (sunk_ships_by_classes) сделать график в colab (X: class, Y: count)
request = """
create view sunk_ships_by_classes as
select s.class, count(name)
from ships s 
join outcomes o 
on s.name = o.ship
group by class
order by count; 
"""

request = """
SELECT * 
FROM sunk_ships_by_classes

"""

df = pd.read_sql_query(request, conn)

request = """
SELECT * 
FROM sunk_ships_by_classes
group by class
order by count;  
"""



df = pd.read_sql_query(request, conn)
fig = px.bar(x=df['class'].to_list(), y=df['count'].to_list(), labels={'x':'class', 'y':'count'})
fig.show()

# По предыдущему view (sunk_ships_by_classes) сделать график в colab (X: class, Y: count)
request = """

select s.class, count(name)
from ships s 
join outcomes o 
on s.name = o.ship
group by class
order by count; 
""" 

df = pd.read_sql_query(request, conn)
fig = px.bar(x=df['class'].to_list(), y=df['count'].to_list(), labels={'x':'class', 'y':'count'})
fig.show()

