# -*- coding: utf-8 -*-
"""Копия блокнота "lesson4"

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U73d3TBA0LjCMehPyuB9TtBYBBBcC7nY
"""

#установка библиотек
# !pip install psycopg2
# !pip install plotly

#проверка подключения PostgreSQL 
import psycopg2
import pandas as pd
#Библиотека ждя визуализации
from IPython.display import HTML
import plotly.express as px


#!введите свои реквизиты!
DB_HOST = '52.157.159.24'
DB_USER = 'student3'
DB_USER_PASSWORD = 'student3_password'
DB_NAME = 'sql_ex_for_student3'

conn = psycopg2.connect(host=DB_HOST, user=DB_USER, password=DB_USER_PASSWORD, dbname=DB_NAME)

#join
request = """
select count(class), country
from classes
group by country
order by count
"""

df = pd.read_sql_query(request, conn)
fig = px.bar(x=df.country.to_list(), y=df.count.to_list(), labels={'x':'country', 'y':'count'})
fig.show()

df.country.to_list()

df.count.to_list()

#join
request = """
select count(name), launched as year
from ships 
group by year
order by count
"""

df = pd.read_sql_query(request, conn)
fig = px.bar(x=df.year.to_list(), y=df.count.to_list(), labels={'x':'year', 'y':'count'})
fig.show()

df.year.to_list()

df.count.to_list()